### ISSUE TITLE
 The file "AgentEnvironments/goals.json" is missing.

### ISSUE THREAD

**Issue by www-Ye** [WooooDyy/AgentGym#17]
I encountered the following error while running the `eval_agentlm_webshop.py` file according to the process in "Evaluation: 01-evaluation":

```
with open("/mnt/petrelfs/chenwenxiang/AgentEnvironments/goals.json","w") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/petrelfs/chenwenxiang/AgentEnvironments/goals.json'
```

How can I resolve this issue? Is it possible that the `goals.json` file has not been released yet?

**Comment by KYLN24** [comment]
Sorry for any inconvenience and thanks for your feeedback. We have fixed this problem in the latest commit. Please `git pull` and retry.
