### ISSUE TITLE
pip install doesn't work

### ISSUE THREAD

**Issue by ishapuri** [WooooDyy/AgentGym#18]
Facing the following error when I do `pip install agentenv`: 

Defaulting to user installation because normal site-packages is not writeable
ERROR: Ignored the following versions that require a different python version: 0.0.1 Requires-Python >=3.10
ERROR: Could not find a version that satisfies the requirement agentenv (from versions: none)
ERROR: No matching distribution found for agentenv

**Comment by KYLN24** [comment]
Thanks for your feedback. The python package has not been uploaded yet. We'll upload it to PyPI later. Currently, you can clone this repo and install it from source.

**Comment by ishapuri** [comment]
thanks!
