### ISSUE TITLE
requests.exceptions.RequestException: Failed to create environment:

### ISSUE THREAD

**Issue by ishapuri** [WooooDyy/AgentGym#20]
I try to follow the directions to set up an evaluation for WebShop (I assume the way to run other tasks is similar but you just activate those servers and then change the task name in the script)

I followed the instructions here and launched the server: https://github.com/WooooDyy/AgentGym/blob/main/docs/tutorials/en/01-evaluation.md

But when I try to run the code provided to get the actual evaluation, I get this error: requests.exceptions.RequestException: Failed to create environment: <Response [500]>

how do I fix this? I followed all the instructions. 

```
python theirEvalCode.py 
/u/isha/miniconda3/envs/agentGym/lib/python3.12/site-packages/transformers/utils/hub.py:124: FutureWarning: Using `TRANSFORMERS_CACHE` is deprecated and will be removed in v5 of Transformers. Use `HF_HOME` instead.
  warnings.warn(
Downloading shards: 100%|█████████████████| 3/3 [00:00<00:00, 448.76it/s]
Loading checkpoint shards: 100%|███████████| 3/3 [00:24<00:00,  8.16s/it]
Traceback (most recent call last):
  File "/u/isha/agents_new/AgentGym/outputs/theirEvalCode.py", line 18, in <module>
    WebshopTask(
  File "/u/isha/agents_new/AgentGym/agentenv/agentenv/envs/webshop.py", line 108, in __init__
    super().__init__(client_args, n_clients, *args, **kwargs)
  File "/u/isha/agents_new/AgentGym/agentenv/agentenv/controller/task.py", line 54, in __init__
    self.clients = [self.env_client_cls(**client_args) for _ in range(n_clients)]
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/u/isha/agents_new/AgentGym/agentenv/agentenv/envs/webshop.py", line 34, in __init__
    raise RequestException(f"Failed to create environment: {ok}")
requests.exceptions.RequestException: Failed to create environment: <Response [500]>
```

**Comment by Yiwen-Ding** [comment]
Hi,
Thank you for providing the details. The error message `<Response [500]>`  typically indicates a server-side error. Could you please provide the output or logs from the server after you launched it?

**Comment by arman-kazemi** [comment]
I found out that the issue is due to a missing folder in webshop directory and solved it as follows:
1. copy https://github.com/princeton-nlp/WebShop/tree/a557a208d03b93c83f4075e66e8746922606e60f/search_engine and all the files in it into https://github.com/WooooDyy/AgentGym/tree/main/agentenv-webshop/webshop
2. run lines 50-56 from setup.sh in webshop https://github.com/WooooDyy/AgentGym/blob/0e89a615adee9112c5d4e8bc36b6c92cb17ab973/agentenv-webshop/webshop/setup.sh#L50

You're good to go.
