### ISSUE TITLE
Question about evolution

### ISSUE THREAD

**Issue by easonyang1996** [WooooDyy/AgentGym#21]
Hi, thanks for releasing such an interesting work!
I have a question about the evolution procedure. According to the objective, if the reward r(e,u,r) is binary, is it just equal to selecting successful trajectories and using them as training data?
I don't know if I understand it correctly. Looking for the reply. :)

**Comment by Yiwen-Ding** [comment]
Hi,

Thank you for your interest! For environments with sparse rewards (like webshop and textcraft, etc.), where the reward is binary, the evolution involves selecting successful trajectories (those with a reward of 1) and using them as training data. Your understanding is correct.
