### ISSUE TITLE
Questions about example training scripts

### ISSUE THREAD

**Issue by arman-kazemi** [WooooDyy/AgentGym#23]
Hi,
I have some questions about parameters in the [agentevol training script](https://github.com/WooooDyy/AgentGym/blob/main/agentenv/examples/agentevol/train_agentevol_multi_task.sh):

1. Where can we get the training data? `iter_data_path="./iter_data/iter_data_all_task"`
2. What's the difference between the test step and the inference step?
3. Where can we get the inference data? 
`inference_file_list=("webshop.json" "alfworld.json" "textcraft.json" "sciworld.json" "sqlgym.json" "wordle.json" "maze.json" "babyai.json" "weather.json" "movie.json" "todo.json" "academia.json" "sheet.json" "webarena.json")`
`cur_inference_file=./small_exploration_data/${inference_file_list[$index]}`
4. What do I need to change to train a model that does NOT use the Llama 2 Chat template?

Thanks,

**Comment by KYLN24** [comment]
Hi, sorry for the late reply.

1. The training data is released on HuggingFace. [AgentGym/AgentTraj-L](https://huggingface.co/datasets/AgentGym/AgentTraj-L)
2. In the AgentEvol algorithm, we do "test step" ("step 2" if I understand you correctly) to evaluate the performance of the model, "inference step" ("step 3" if I understand you correctly) to collect trajectories for the training iteration.
3. The inference data for training is AgentTraj-L (as is shown in "1."), for evaluation [AgentGym/AgentEval](https://huggingface.co/datasets/AgentGym/AgentEval)
4. Currently, we have hard-coded the chat template for Llama 2 Chat in `agentenv.controller.task.BaseTask._tokenize_conversation_one` and many other training scripts. Sorry for this bad design. We've refactored how AgentGym tokenizes messages in a more modular way. As for now, you can modify this function to adapt to other templates.

Feel free to re-open this issue if further discussion is needed.
