### ISSUE TITLE
可以在readme指明那些环境需要docker/外网吗

### ISSUE THREAD

**Issue by Fu-Dayuan** [WooooDyy/AgentGym#24]
如题，我感觉是不是就是webarea和tool系列需要

**Comment by KYLN24** [comment]
基本不太需要使用 docker。

我们没有特意关注国内网络无法直接连接的情况。一般而言，部分环境可能会把某些数据放在 Google Drive 等地方，可以通过对应环境的 setup.sh 等或观察安装过程中的终端输出来判断。

如需进一步讨论，欢迎重新打开这个 issue。
