### ISSUE TITLE
运行conda create -n webshop -f environment.yml 遇到问题

### ISSUE THREAD

**Issue by pokerme7777** [WooooDyy/AgentGym#26]
你好，想问一下运行conda create -n webshop -f environment.yml的过程中遇到了安装问题：
Retrieving notices: ...working... done
Channels:
 - defaults
Platform: linux-64
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - environment.yml

Current channels:

  - defaults

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

请问一下应该如何解决

**Comment by KYLN24** [comment]
您好，你可以先直接创建环境，然后参考 environment.yml 安装对应版本的 python、faiss 和 openjdk。
```bash
conda create -n webshop
conda activate webshop
conda install python=3.8 faiss-cpu=1.7 openjdk=11
```

**Comment by K1nght** [comment]
The command syntax `conda create -n webshop -f environment.yml` is incorrect. The `-f` parameter should be used with `conda env create`. The correct command is:

```
conda env create -n webshop -f environment.yml
```
which works for me.

**Comment by pokerme7777** [comment]
Thanks a lot!
