### ISSUE TITLE
License of the AgentTraj-L Data?

### ISSUE THREAD

**Issue by jianguoz** [WooooDyy/AgentGym#29]
Hi Authors,

We are highly impressed with the work as it significantly simplifies the use of agent environments!

Additionally, we appreciate the release of [AgentTraj-L](https://huggingface.co/datasets/AgentGym/AgentTraj-L) data and are eager to explore it further. 

However, we noticed that there is no associated license for AgentTraj-L. Could you please provide information on the corresponding license?

**Comment by KYLN24** [comment]
As is specified in our paper, AgentTraj is produced by these sources:

- Trajectories generated by GPT or Llama models on corresponding environments.
- The raw or augmented trajectories from [THUDM/AgentInstruct](https://huggingface.co/datasets/THUDM/AgentInstruct).

We release this dataset only for research purposes. You should follow the Licenses of OpenAI, Meta Llama and other related works.

Feel free to re-open this issue if further discussion is needed.
