### ISSUE TITLE
Issues running Webarena

### ISSUE THREAD

**Issue by rowingchenn** [WooooDyy/AgentGym#34]
Server output:

Traceback (most recent call last):
  File "/home/ubuntu/AgentGym_OOD/agentenv-webarena/webarena/browser_env/auto_login.py", line 169, in <module>
    main()
  File "/home/ubuntu/AgentGym_OOD/agentenv-webarena/webarena/browser_env/auto_login.py", line 160, in main
    assert not future.result(), f"Cookie {cookie_files[i]} expired."
AssertionError: Cookie ./.auth/gitlab.reddit_state.json expired.

Through printing information, I found Inconsistent expired results that happened to cookie files.
How should I address this problem?

**Comment by hotdog-zz** [comment]
First, log in to the GITLAB website. If you have not modified our setup.sh, the website address should be: http://ec2-3-131-244-37.us-east-2.compute.amazonaws.com:8023.
Then, try logging in with the following username and account: {"username": "byte", "password": "hello"}.
If prompted that the account does not exist, try to register with the above username and password, and then try your code again.

**Comment by rowingchenn** [comment]
Hi, it seems that all the Webarena websites you provided are not working. Could you check it? Thank you!

**Comment by KYLN24** [comment]
Hello, the URL is provided by the original author of webarena (https://webarena.dev/). It seems that they have shut down this website. You can follow their instructions to set up your own webarena website and use it in AgentGym by setting some env_vars. Their GitHub link is https://github.com/web-arena-x/webarena

Feel free to re-open this issue if any further discussion is needed.
